---
server:
  context-path: /api
documentation:
  swagger:
    services:
      -
        name: Animal Service
        url: /animals/api-docs
        version: 2.0
      - 
        name: Human Service
        url: /humans/api-docs
        version: 2.0